CREATE TABLE user_role (
    user_id int8 not null,
    roles varchar(255)
);

CREATE TABLE users (
    id int8 generated by default as identity,
    date_created int8 not null,
    date_updated int8,
    status varchar(255),
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
);

ALTER TABLE IF EXISTS user_role ADD CONSTRAINT user_role_fk
    FOREIGN KEY (user_id) REFERENCES users